version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      RAILS_ENV: development

  db:
    image: keinos/sqlite3:latest
    volumes:
      - db_data:/db

volumes:
  db_data: